name: love_novel
description: Novel World - Fiction Novels & Romance Stories

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.3+23

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  basic_utils: ^4.2.2
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.4
  date_time_picker: ^2.1.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  flutter_html: ^2.2.1
  flutter_local_notifications: ^9.5.3+1
  flutter_native_splash: ^2.1.6
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^0.23.0+1
  font_awesome_flutter: ^10.1.0
  get: ^4.6.3
  hive: ^2.1.0
  shared_preferences: ^2.0.15
  flutter_ironsource_x: ^2.7.1
  firebase_core: ^1.17.0
  firebase_performance: ^0.8.0+12
  flutter_screenutil: ^5.5.2
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.0
  random_string: ^2.3.1
  google_mobile_ads: ^1.2.0
  in_app_review: ^2.0.4
  path_provider: ^2.0.10
  upgrader: ^4.1.1
  in_app_purchase: ^3.0.4
  permission_handler: ^9.2.0
  flutter_share: ^2.0.0
  uuid: ^3.0.6
  applovin_max: ^2.3.2
  firebase_analytics: ^9.1.11
  change_app_package_name: ^1.1.0
  device_preview: ^1.1.0
  appsflyer_sdk: ^6.9.3
  loading_animation_widget: ^1.2.0+4
  firebase_remote_config: ^2.0.10
  # flutter_login_facebook: ^1.4.1

dev_dependencies: 
  build_runner: ^2.1.10
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.2
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1


flutter_app_name:
  name: "Novel World"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/themes/
    - .env

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700

    - family: Charm
      fonts:
        - asset: assets/fonts/Charm-Regular.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Normal.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 500

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin-Regular.ttf
          style: italic
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cabin-BoldItalic.ttf
          style: italic
          weight: 700

    - family: Bellota
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
        - asset: assets/fonts/Bellota-italic.ttf
          style: italic
        - asset: assets/fonts/Bellota-Bold.ttf
          weight: 700
        - asset: assets/fonts/Bellota-BoldItalic.ttf
          style: italic
          weight: 700

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-italic.ttf
          style: italic

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf