// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH6s8o2ibCrkZJK2KXBzMKY-Gn3gRKaJQ',
    appId: '1:878415765408:web:c733f0522b64d608544ec5',
    messagingSenderId: '878415765408',
    projectId: 'inovel-d904a',
    authDomain: 'inovel-d904a.firebaseapp.com',
    storageBucket: 'inovel-d904a.appspot.com',
    measurementId: 'G-RKVGQL5S7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEO1QPNdjUpKry_bEdbAc6Q8J-V0s997M',
    appId: '1:878415765408:android:17d0c131293f6b7d544ec5',
    messagingSenderId: '878415765408',
    projectId: 'inovel-d904a',
    storageBucket: 'inovel-d904a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-5_6wIEGQ8V4w_mDqLp_6A-zd2SCGSuU',
    appId: '1:878415765408:ios:bcea828844794951544ec5',
    messagingSenderId: '878415765408',
    projectId: 'inovel-d904a',
    storageBucket: 'inovel-d904a.appspot.com',
    androidClientId: '878415765408-dj0nb6nhoiamom7rnp62mlsqer1mjpr6.apps.googleusercontent.com',
    iosClientId: '878415765408-e7f2vlm689s4k57laeei3hnphhhf5gn0.apps.googleusercontent.com',
    iosBundleId: 'com.novelwordstudio.booklovenovelfull',
  );
}
